[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
  force = true

[[redirects]]
  from = "/crm"
  to = "/crm/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/crm/"
  to = "/crm/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
